#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build:
    context: ..
    dockerfile: docker/dockerfile
  image: pomelo925/rl-app:piano

  volumes:
    # GUI support for ROS applications
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix
    
    # Workspace volume
    - ../workspace:/workspace

  environment:
    - DISPLAY=${DISPLAY}

  network_mode: "host"
  ipc: host
  

  tty: true
  stdin_open: true
  privileged: true
  stop_grace_period: 1s
  working_dir: /workspace

############################
###   GPU settings       ###
############################
x-gpu-settings: &gpu
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all


##############################
###   Container Services   ###
##############################
services:
  dev:
    <<: [*common, *gpu]
    container_name: piano-dev
    command: ["/bin/bash"]
  deploy:
    <<: [*common, *gpu]
    container_name: piano-deploy
    command: ["/bin/bash"]